# TCL File Generated by Component Editor 18.1
# Thu Dec 01 10:22:29 CET 2022
# DO NOT MODIFY


# 
# verin "verin" v1.0
#  2022.12.01.10:22:29
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module verin
# 
set_module_property DESCRIPTION ""
set_module_property NAME verin
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME verin
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_verin
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_verin.vhd VHDL PATH ../../../src/f6/avalon_verin.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter G_FREQ_IN INTEGER 50000000
set_parameter_property G_FREQ_IN DEFAULT_VALUE 50000000
set_parameter_property G_FREQ_IN DISPLAY_NAME G_FREQ_IN
set_parameter_property G_FREQ_IN TYPE INTEGER
set_parameter_property G_FREQ_IN UNITS None
set_parameter_property G_FREQ_IN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property G_FREQ_IN HDL_PARAMETER true
add_parameter G_FREQ_ADC INTEGER 1000000
set_parameter_property G_FREQ_ADC DEFAULT_VALUE 1000000
set_parameter_property G_FREQ_ADC DISPLAY_NAME G_FREQ_ADC
set_parameter_property G_FREQ_ADC TYPE INTEGER
set_parameter_property G_FREQ_ADC UNITS None
set_parameter_property G_FREQ_ADC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property G_FREQ_ADC HDL_PARAMETER true


# 
# display items
# 


# 
# connection point external_connection
# 
add_interface external_connection conduit end
set_interface_property external_connection associatedClock ""
set_interface_property external_connection associatedReset ""
set_interface_property external_connection ENABLED true
set_interface_property external_connection EXPORT_OF ""
set_interface_property external_connection PORT_NAME_MAP ""
set_interface_property external_connection CMSIS_SVD_VARIABLES ""
set_interface_property external_connection SVD_ADDRESS_GROUP ""

add_interface_port external_connection cs_n_o cs_n_o Output 1
add_interface_port external_connection pwm_o pwm_o Output 1
add_interface_port external_connection sck_o sck_o Output 1
add_interface_port external_connection sdi_i sdi_i Input 1
add_interface_port external_connection sens_o sens_o Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock ""
set_interface_property reset synchronousEdges NONE
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset arst_i reset Input 1


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_i clk Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock clk
set_interface_property s1 associatedReset reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 maximumPendingWriteTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 CMSIS_SVD_VARIABLES ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 write_data_i writedata Input 32
add_interface_port s1 read_data_o readdata Output 32
add_interface_port s1 address_i address Input 3
add_interface_port s1 write_i write Input 1
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0

